SELECT SPRIDEN.SPRIDEN_PIDM AS PIDM_IND,
       SPRIDEN.SPRIDEN_ID AS STUDENT_ID_IND,
       TO_CHAR(SPBPERS.SPBPERS_BIRTH_DATE,'YYYY') as "BIRTH_YEAR",
       TO_CHAR(SPBPERS.SPBPERS_BIRTH_DATE, 'YYYY-MM-DD') as BIRTH_DATE,
       (sysdate - SPBPERS.SPBPERS_BIRTH_DATE) as "DAYS_SINCE_BIRTH",
       TO_CHAR(sysdate, 'YYYY-MM-DD') as "EXTRACT_DATE",
       SPBPERS.SPBPERS_SEX
  FROM REPORTS.ENROLLED_STUDENTS_BY_TERM ENROLLED_STUDENTS_BY_TERM
       LEFT JOIN SATURN.SPRIDEN SPRIDEN
          ON     SPRIDEN.SPRIDEN_ID = ENROLLED_STUDENTS_BY_TERM.STUDENT_ID
             AND SPRIDEN.SPRIDEN_CHANGE_IND IS NULL
       LEFT JOIN SPBPERS ON spriden.SPRIDEN_PIDM = SPBPERS.SPBPERS_PIDM
 WHERE     1 = 1
       AND ENROLLED_STUDENTS_BY_TERM.TERM_CODE = :term_code
       AND ENROLLED_STUDENTS_BY_TERM.PRIMARY_DEGREE_CAMPUS = 'A'
