SELECT REGREM.STUDENT_PIDM AS PIDM_IND,
       SUM (REGREM.CREDIT_ATTEMPTED) AS CREDITS
  FROM DSDMGR.DSD_REGISTRATION_OPEN REGREM
       INNER JOIN DSDMGR.DSD_STUDENT_STATS_OPEN STUD
          ON     REGREM.STUDENT_PIDM = STUD.STUDENT_PIDM
             AND REGREM.TERM_CODE = STUD.TERM_CODE
             AND STUD.ACADEMIC_ORGANIZATION = 'AC'
 WHERE     1 = 1
       AND TO_NUMBER (REGEXP_REPLACE (REGREM.COURSE_NUMBER, '[^0-9]+', '')) BETWEEN 50
                                                                                AND 99
       AND REGREM.REGISTRATION_STATUS NOT LIKE 'W%'
       AND REGREM.REGISTRATION_STATUS NOT LIKE 'D%'
GROUP BY REGREM.STUDENT_PIDM
