SELECT Username,
       cldemo.FirstName,
       PreferredFirstName,
       MiddleName,
       cldemo.LastName,
       Suffix,
       Hometown,
       Affiliation,
       CampusEmail,
       PreferredEmail,
       CardID,
       SISID,
       MobilePhone,
       CONVERT(VARCHAR(10),DateOfBirth,101) AS "DateOfBirth",
       Sex,
       Race,
       Ethnicity,
       EnrollmentStatus,
       CurrentTermEnrolled,
       CurrentTermGPA,
       PreviousTermEnrolled,
       PreviousTermGPA,
       CreditHoursEarned,
       AnticipatedDateOfGraduation,
       CareerLevel,
       ClassStanding,
       PrimarySchoolOfEnrollment,
       DegreeSought,
       Major,
       Minor,
       MajorAdvisor,
       OtherAdvisor,
       LocalResidencyStatus,
       CASE
          WHEN housing.StudentNumber IS NOT NULL THEN 'On-campus'
          ELSE 'Off campus'
       END
          AS HousingFacility,
       International,
       [Transfer],
       Athlete,
       AthleticParticipation,
       LocalPhoneCountryCode,
       LocalPhone,
       LocalPhoneExtension,
       LocalStreet1,
       LocalStreet2,
       LocalStreet3,
       LocalCity,
       LocalStateProvince,
       LocalPostalCode,
       LocalCountry,
       HomePhoneCountryCode,
       HomePhone,
       HomePhoneExtension,
       HomeStreet1,
       HomeStreet2,
       HomeStreet3,
       HomeCity,
       HomeStateProvince,
       HomePostalCode,
       HomeCountry,
       AbroadPhoneCountryCode,
       AbroadPhone,
       AbroadPhoneExtension,
       AbroadStreet1,
       AbroadStreet2,
       AbroadStreet3,
       AbroadCity,
       AbroadStateProvince,
       AbroadPostalCode,
       AbroadCountry
  FROM rptp.campuslabs.demographics cldemo
       LEFT JOIN csv.dbo.housing housing
          ON     cldemo.SISID = housing.StudentNumber
             AND housing.Term_Code = :current_term
