SELECT DEMOG.FISCAL_YEAR,
       DEMOG.TERM_CODE AS TERM_CODE_IND,
       DEMOG.STUDENT_PIDM AS STUDENT_PIDM_IND,
       DEMOG.UA_ID AS UA_ID_IND,
       DEMOG.UAR_RACE,
       DEMOG.IPEDS_RACE,
       DEMOG.HISP_FLAG,
       DEMOG.GENDER,
       TO_CHAR(DEMOG.BIRTH_DATE, 'MM/DD/YYYY') AS BIRTH_DATE,
       DEMOG.CENSUS_AGE,
       DEMOG.ORIGIN_AT_ENTRY,
       DEMOG.CITZ_CODE,
       DEMOG.VISA_CODE,
       DEMOG.RESIDENCY_CODE,
       DEMOG.MARITAL_STATUS,
       DEMOG.UASUER_ID,
       DEMOG.RATE_CODE
  FROM DSDMGR.DSD_STUDENT_DEMOG_CLOS DEMOG
       INNER JOIN DSDMGR.DSD_STUDENT_STATISTICS STATS
         ON     DEMOG.STUDENT_PIDM = STATS.STUDENT_PIDM
            AND DEMOG.TERM_CODE = STATS.TERM_CODE
            AND STATS.MAU = 'UAA'
 WHERE     1 = 1
       AND DEMOG.FISCAL_YEAR > 2010