/**
 *
 * Pulls usernames for current term students (based on opening freeze)
 * and current employees/faculty (based on active_assignemnts).
 *
 */
SELECT GOBTPAC_PIDM AS PIDM_IND,
       STATS.STUDENT_ID AS UA_ID_IND,
       GOBTPAC.GOBTPAC_EXTERNAL_USER AS USERNAME_IND
  FROM GOBTPAC
       INNER JOIN DSDMGR.DSD_STUDENT_STATS_OPEN STATS
          ON     STATS.TERM_CODE = :current_term
             AND STATS.STUDENT_PIDM = GOBTPAC.GOBTPAC_PIDM
             AND STATS.HOME_CAMPUS = 'A'
UNION
SELECT GOBTPAC.GOBTPAC_PIDM AS PIDM_IND,
       AA.EMPLOYEE_ID AS UA_ID_IND,
       GOBTPAC.GOBTPAC_EXTERNAL_USER AS USERNAME
  FROM GOBTPAC
       LEFT JOIN SPRIDEN
          ON     SPRIDEN.SPRIDEN_PIDM = GOBTPAC.GOBTPAC_PIDM
             AND SPRIDEN.SPRIDEN_CHANGE_IND IS NULL
             AND SPRIDEN.SPRIDEN_ID LIKE '3%'
       INNER JOIN DSDMGR.DSD_ACTIVE_ASSIGNMENTS AA
          ON     SPRIDEN.SPRIDEN_ID = AA.EMPLOYEE_ID
             AND AA.CHK_TKL BETWEEN 'T600' AND 'T799'
