SELECT SGRSPRT_PIDM AS PIDM_IND,
       SGRSPRT.SGRSPRT_ACTC_CODE,
       STVACTC.STVACTC_DESC,
       CASE
          WHEN SGRSPRT_ACTC_CODE = 'AGYM' THEN 12
          WHEN SGRSPRT_ACTC_CODE = 'AHKY' THEN 15
          WHEN SGRSPRT_ACTC_CODE = 'AMBB' THEN 2
          WHEN SGRSPRT_ACTC_CODE = 'AMRUN' THEN 5
          WHEN SGRSPRT_ACTC_CODE = 'AMSKI' THEN 24
          WHEN SGRSPRT_ACTC_CODE = 'AMTO' THEN 35
          WHEN SGRSPRT_ACTC_CODE = 'AVBALL' THEN 36
          WHEN SGRSPRT_ACTC_CODE = 'AWBB' THEN 1
          WHEN SGRSPRT_ACTC_CODE = 'AWSKI' THEN 23
          WHEN SGRSPRT_ACTC_CODE = 'AWTO' THEN 34
          ELSE 41
       END
          AS "AthleteSport",
       CASE WHEN SGRSPRT_ATHL_AID_IND = 'Y' THEN 1 ELSE 0 END
          AS "AthleteScholarship"
  FROM SGRSPRT
       LEFT JOIN STVACTC ON STVACTC.STVACTC_CODE = SGRSPRT.SGRSPRT_ACTC_CODE
 WHERE SGRSPRT_TERM_CODE = :current_term AND SGRSPRT.SGRSPRT_ACTC_CODE LIKE 'A%'
