SELECT DISTINCT
       ENROLLED_STUDENTS_BY_TERM.TERM_CODE AS TERM_CODE,
       SPRIDEN.SPRIDEN_PIDM AS PIDM_IND,
       ENROLLED_STUDENTS_BY_TERM.PRIMARY_DEGREE_CAMPUS AS CAMPUS,
       ENROLLED_STUDENTS_BY_TERM.ENROLLED_IND AS ENROLLED,
       ENROLLED_STUDENTS_BY_TERM.PRIVACY_IND AS PRIVACY,
       ENROLLED_STUDENTS_BY_TERM.STUDENT_ID AS STUDENT_ID_IND,
       ENROLLED_STUDENTS_BY_TERM.STUDENT_NAME_LAST,
       ENROLLED_STUDENTS_BY_TERM.STUDENT_NAME_FIRST,
       ENROLLED_STUDENTS_BY_TERM.STUDENT_NAME_MI,
       ENROLLED_STUDENTS_BY_TERM.CLASS_STANDING AS CLASS_STANDING,
       ENROLLED_STUDENTS_BY_TERM.PRIMARY_DEGREE_STUDENT_LEVEL
          AS PRIMARY_DEG_LEVEL,
       ENROLLED_STUDENTS_BY_TERM.PRIMARY_DEGREE_COLLEGE AS PRIM_COLLEGE,
       STVCOLL.STVCOLL_DESC AS PRIM_COLL_DESC,
       ENROLLED_STUDENTS_BY_TERM.PRIMARY_DEGREE_CODE AS PRIM_DEGREE_CODE,
       ENROLLED_STUDENTS_BY_TERM.PRIMARY_MAJOR_CODE_1 AS PRIM_MAJR,
       STVMAJR.STVMAJR_DESC AS PRIM_MAJR_DESC,
       STVMAJR.STVMAJR_CIPC_CODE
  FROM REPORTS.ENROLLED_STUDENTS_BY_TERM ENROLLED_STUDENTS_BY_TERM
       LEFT JOIN SATURN.SPRIDEN SPRIDEN
          ON     SPRIDEN.SPRIDEN_ID = ENROLLED_STUDENTS_BY_TERM.STUDENT_ID
             AND SPRIDEN.SPRIDEN_CHANGE_IND IS NULL
             AND SPRIDEN.SPRIDEN_ID LIKE '3%'
       LEFT JOIN SATURN.STVMAJR STVMAJR
          ON STVMAJR.STVMAJR_CODE =
                ENROLLED_STUDENTS_BY_TERM.PRIMARY_MAJOR_CODE_1
       LEFT JOIN SATURN.STVCOLL STVCOLL
          ON STVCOLL.STVCOLL_CODE =
                ENROLLED_STUDENTS_BY_TERM.PRIMARY_DEGREE_COLLEGE
       INNER JOIN CLASS_LIST
          ON     ENROLLED_STUDENTS_BY_TERM.STUDENT_ID = CLASS_LIST.STUDENT_ID
             AND class_list.current_term = :current_term
             AND CLASS_LIST.COURSE_CAMPUS = 'A'
             AND CLASS_LIST.COURSE_SECTION NOT LIKE '2%'
             AND CLASS_LIST.COURSE_SECTION NOT LIKE '5%'
             AND CLASS_LIST.COURSE_SECTION NOT LIKE '8%'
             AND class_list.registration_status_code NOT IN ('AU', 'FW')
             AND class_list.registration_status_code NOT LIKE 'W%'
 WHERE     1 = 1
       AND ENROLLED_STUDENTS_BY_TERM.TERM_CODE = :current_term
       AND enrolled_students_by_term.CLASS_STANDING IN ('FR',
                                                        'JR',
                                                        'ND',
                                                        'PD',
                                                        'SO',
                                                        'SR')
       AND ENROLLED_STUDENTS_BY_TERM.PRIMARY_DEGREE_CAMPUS = 'A'
